### PR TITLE
Add Django 1.9 compatibility

### PR DESCRIPTION
**Pull request by jlesech**
I'm not sure it's the correct way to solve issue #66... Let me know!

### CODE REVIEW

**Comment by microniko** [comment]
This patch works fine for me :+1:

**Comment by leplatrem** [comment]
Test suite is broken because of `ValueError: Cannot use object with type Polygon for a geometry lookup parameter.`

**Comment by leplatrem** [comment]
Related #66

**Comment by AchilleAsh** [comment]
Hi @leplatrem ,

In order to fix the ValueError with Polygon, you have to change the import in the views.py (line 10):

```python
    from django.contrib.gis.geos import Polygon
```

Before 1.9 it was

```python
    from django.contrib.gis.geos.geometry import Polygon
```

Test suite is running fine with this fix on my computer and I see no strange behaviour in my Django app.

Thank you for your work :)

**Comment by leplatrem** [comment]
Thanks @AchilleAsh for the kind words!

The thing is: I don't work at _Makina Corpus_ anymore and can't invest time since I have no necessity of this in my current job.

If you submit a pull-request where the tests pass, I can still merge it and release though.

Thanks!

**Comment by jlesech** [comment]
I'll open a better one...

**Pull request closed without merging**
