### PR TITLE
Django 1.8 - Nogeos.

### PR DESCRIPTION
**Pull request by batisteo**
This is kind of monkey patching too, that make my code works under Python 3, Django 1.8 and with django-leaflet.

### CODE REVIEW

**Comment by leplatrem** [comment]
Since I don't use this tool anymore, and I don't think @gutard uses it without GEOS.
I would be ok to trust this change :)

I let the guyz at Makina merge this.

**Comment by leplatrem** [comment]
Apparently github notifications are filtered...

**Comment by batisteo** [comment]
I'm sorry, I don't use it anymore either. It was a bit overkill.

**Comment by leplatrem** [comment]
Closing then!

**Pull request closed without merging**
