### PR TITLE
Support Django 3.2

### PR DESCRIPTION
**Pull request by adamchainz**
* Add to tox and travis setups.
* Update `quicktest.py` with new required settings, and drop old Django and Python code.

### CODE REVIEW

**Comment by adamchainz** [comment]
I didn't check the tox file since I haven't done the spatialite setup localy.

**Comment by Gagaro** [comment]
Thanks for the cleanup.

I'll set up Github Actions first before merging this PR. Thanks for the example, but I don't like not having a job for each environment (python version + django version).

I agree with you on duplicating the matrices though. I remember something doing a job per tox environment on travis and there seems to be something equivalent for gh actions (https://github.com/ymyzk/tox-gh-actions), I'll try that.

(Also, you should hide your coveralls token in your secrets).

**Comment by adamchainz** [comment]
I used to use `tox-gh-actions` but dropped it because I felt it was unnecessary to add extra config. I do one job per Python version, with a shell one liner to select the relevant versions. Check out my open source projects for example: https://github.com/adamchainz/django-htmx/blob/main/.github/workflows/main.yml

**Comment by Gagaro** [comment]
I ended up copying the action from django-leaflet, it seems there are still tests failings but I need some of your fix for the last version.

**Comment by adamchainz** [comment]
Great, thanks.

**Pull request merged**
