### PR TITLE
Set default initial value to form field

### PR DESCRIPTION
**Pull request by Vayel**
See #115

### CODE REVIEW

**Comment by Gagaro** [comment]
Thanks for the PR :+1:

**Comment by Vayel** [comment]
@Gagaro is it possible to make a release with this change? In non-dev model, the error raises an exception, what is quite annoying.

Many thanks!

**Comment by Gagaro** [comment]
Sure, released in 3.2.1.

**Comment by Vayel** [comment]
Many thanks!

**Pull request merged**
