### PR TITLE
Fix warning on Django 3.1

### PR DESCRIPTION
**Pull request by adamchainz**
Fix this warning raised from Django 3.1 onwards:

```
venv/lib/python3.8/site-packages/djgeojson/fields.py:60
  /.../venv/lib/python3.8/site-packages/djgeojson/fields.py:60: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    description = _("Geometry as GeoJSON")
```

Also add Django 3.1 to the travis definition.

### CODE REVIEW

**Comment by gutard** [comment]
I propose to fix Django minimal version to 2.0 and to require Python 3. So we can use gettext instead of ugettext unconditionnaly. @Gagaro what do you think about that  ?

**Comment by Gagaro** [comment]
We can even support from 2.2 as 2.0/2.1 are no longer supported.

I'm up for dropping 1.11 anyway.

**Comment by adamchainz** [comment]
I've pushed a change to drop Python 2 and Django < 2.2 This includes the removal of six, the declaration of the minimum python version with `python_requires`, and pinning in `install_requires`.

I've also set all deprecation warnings and pending deprecation warnings in tests to error. This avoids them accidentally creeping back in future PR's when adding e.g. new django versions. As a library it's best not to pass such warnings on to users.

**Comment by Gagaro** [comment]
Thanks for the follow up, there still is a `string_types` reference in `serializers.py` line 504.

> I've also set all deprecation warnings and pending deprecation warnings in tests to error. This avoids them accidentally creeping back in future PR's when adding e.g. new django versions. As a library it's best not to pass such warnings on to users.

Yes I like that too :+1: .

**Comment by adamchainz** [comment]
I've fixed all the test failures now, but the coverage is dropping because the number of lines of code is decreasing.

**Comment by Gagaro** [comment]
Thanks for the PR :+1: .

**Pull request merged**
